#!/usr/bin/env bash

sudo apt install i3 picom nitrogen lxappearance rofi lsd zsh tmux fzf xclip ripgrep fd-find zoxide mate-polkit btop -y

ln -sf ~/opt/dotfiles/scripts ~/.config/scripts
ln -sf ~/opt/dotfiles/nvim ~/.config/nvim
ln -sf ~/opt/dotfiles/i3 ~/.config/i3
ln -sf ~/opt/dotfiles/awesome-config/rofi ~/.config/rofi
ln -sf ~/opt/dotfiles/picom ~/.config/picom

ln -sf ~/opt/dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/opt/dotfiles/zsh/.zshenv ~/.zshenv
ln -sf ~/opt/dotfiles/tmux/.tmux.conf ~/.tmux.conf

if [ ! -d ~/.config/btop ]; then
    mkdir ~/.config/btop
fi && \
ln -sf ~/opt/dotfiles/btop/btop.conf ~/.config/btop/btop.conf

#install JetBrainsMono font
if [ ! -d ~/.local/share/fonts ]; then
    mkdir ~/.local/share/fonts
fi && \
wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip && \
cd ~/.local/share/fonts && \
unzip JetBrainsMono.zip && \
rm JetBrainsMono.zip && \
fc-cache -fv

chsh -s $(which zsh)
