set -g mode-keys vi
set -g mouse on
set -g history-limit 10000
set -s escape-time 0
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides "xterm-256color*:Tc"
set-option -g focus-events on
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Navigation bindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Window management
bind-key & kill-window
bind-key x kill-pane
set-option -g renumber-windows on

# Copy-paste bindings
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind P paste-buffer

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Sessionizer
bind-key -r f run-shell "tmux neww ~/.config/scripts/sessionizer"

##### THEME #####

# Core colors
set -g status-position top
set -g status-justify left
set -g status-style "bg=default,fg=#708183"

set -g status-left-length 60
set -g status-right-length 100

# Status Left
set -g status-left "#[fg=#fcf4dc,bg=#002731,bold]  #S #[fg=#002731,bg=default] "

# Status Right
set -g status-right "#[fg=#259185,bg=default]#[fg=#000000,bg=#259185] 󰥔 %H:%M #[fg=#2075c7,bg=#259185]#[fg=#000000,bg=#2075c7] 󰃭 %d %b #[fg=#c61b6e,bg=#2075c7]#[fg=#fcf4dc,bg=#c61b6e]  #(whoami)@#h "

# Window styling
setw -g window-status-style "fg=#708183,bg=default"
setw -g window-status-current-style "fg=#fcf4dc,bg=default,bold"

setw -g window-status-format " #I:#W "

setw -g window-status-current-format "#[fg=#002731,bg=default]#[fg=#fcf4dc,bg=#002731,bold] #I:#W#{?window_zoomed_flag, 🔍,} #[fg=#002731,bg=default]"

setw -g window-status-separator ""

# Pane borders
set -g pane-border-style "fg=#465a61"
set -g pane-active-border-style "fg=#259185"

# Messages
set -g message-style "bg=#002731,fg=#fcf4dc,bold"
set -g message-command-style "bg=#002731,fg=#259185"

# Copy mode / selection
set -g mode-style "bg=#002731,fg=#fcf4dc"

# Clock mode
setw -g clock-mode-colour "#2075c7"

# Pane number display
set -g display-panes-active-colour "#259185"
set -g display-panes-colour "#708183"
