#!/bin/env bash

# Find the touchpad device
touchpad_id=$(xinput list | grep -i 'touchpad' | grep -o 'id=[0-9]\+' | grep -o '[0-9]\+')

if [ -n "$touchpad_id" ]; then
    # Enable tapping
    xinput set-prop "$touchpad_id" "libinput Tapping Enabled" 1
    
    # Enable natural scrolling
    xinput set-prop "$touchpad_id" "libinput Natural Scrolling Enabled" 1
else
    echo "Touchpad not found"
fi
