[main]
terminal=kitty
mode=list
lines=15
width=50
horizontal-pad=20
vertical-pad=10
inner-pad=12
image-size-ratio=0.8
show-actions=yes
icon-theme=Adwaita
font=JetBrainsMono Nerd Font:size=11
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
# Base
background=000000e6
text=708183ff
prompt=fcf4dcff
placeholder=465a61ff
input=fcf4dcff
match=259185ff

# Selection
selection=002731ff
selection-match=2075c7ff
selection-text=fcf4dcff

# UI
counter=708183ff
border=259185ff

[border]
width=3
radius=8

[key-bindings]
cancel=Escape Control+c
execute=Return KP_Enter
execute-or-next=Tab

cursor-left=Left Control+b
cursor-right=Right Control+f
cursor-home=Home Control+a
cursor-end=End Control+e

prev=Up Control+p ISO_Left_Tab Control+k
next=Down Control+n Tab Control+j

first=Page_Up Control+Home
last=Page_Down Control+End

delete-prev=BackSpace Control+h
delete-next=Delete Control+d
delete-prev-word=Control+BackSpace Control+w

delete-line-backward=Control+u
delete-line-forward=Control+k

clear=Control+l
