#!/usr/bin/env bash

selected_name=$(pwd | sed 's/.*\///g' | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux -u new-session -s $selected_name
	exit 0
fi

if ! tmux -u has-session -t=$selected_name 2>/dev/null; then
	tmux -u new-session -ds $selected_name
fi

tmux -u switch-client -t $selected_name
